### ISSUE TITLE
Page Blank

### ISSUE THREAD

**Issue by tmepyans** [bcholmes/StarTrek2d20#168]
On mobile (Samsung Galaxy S22), if you go with Captain's Log and select a race, the following page is just black with no controls. Thanks for all your hard work!

**Comment by bcholmes** [comment]
Hm. I haven't been able to reproduce this. Does this happen consistently, or just once? Do you remember what species you're selecting?

**Comment by tmepyans** [comment]
It's with any race of I'm doing Captain's Log. I used the stock Samsung internet, and Chrome.

**Comment by bcholmes** [comment]
Okay. I suspect that the problem is specific to that browser. The problem is: I don't have that browser, so I don't know how to replicate the problem. 

How viable would it be for you to access the [console log](https://android.stackexchange.com/questions/131781/how-to-properly-debug-websites-on-the-samsung-browser)? There's probably an error message there that'd help me understand what's happening. If you could screenshot the error or something, that'd help me understand.

**Comment by tmepyans** [comment]
I tried it on Firefox with the same result, but I switched it to desktop and it worked fine. 🤷‍♂️

**Comment by bcholmes** [comment]
Actually, that helped to know. I have an Android device with Firefox, so I was able to reproduce the problem. I should be able to push a fix soonish.
