### ISSUE TITLE
Suggestion for spaceframe: cetacean deep space explorer

### ISSUE THREAD

**Issue by ambassadordan** [bcholmes/StarTrek2d20#60]
Cetacean deep space explorer, Shackleton expanse p. 286

**Comment by bcholmes** [comment]
It seems like the book, itself, does not describe the spaceframe -- it stats up a full ship, rather than a separate spaceframe and mission profile.

**Comment by Felderburg** [comment]
It also notes that the ship sent to the Expanse is an SS, not USS. Which isn't a problem, necessarily, as civilian ships could very well be something the tool could provide, but I think in this case it adds to the evidence that this is a special type of ship, built "as-is," rather than a frame with profiles.

**Comment by bcholmes** [comment]
I think the "Simplified Starship" workflow is probably the best way to handle this kind of thing.
