### ISSUE TITLE
Ocampa Telepathy

### ISSUE THREAD

**Issue by Felderburg** [bcholmes/StarTrek2d20#94]
When full species is selected, telepath is not shown as an Ocampa talent. It is shown when Mixed Species is chosen.

Additionally, when full Ocampa is the species, allowing cross-species talents shows only the Betazoid version of telepath, which does have a different description from the Ocampa version.

**Comment by bcholmes** [comment]
So it looks like one of the root problems is that there are multiple instances of the "Empath" and "Telepath" talents, and parts of the code clearly assume that the talent names are unique. There was an addition mistake in that the Ocampa was listed as having an "Empath" talent option rather than a "Telepath" talent option. Should be fixed, now.

**Comment by Felderburg** [comment]
Seems to be... although it is worth noting that the description of the Ocampan telepath talent is quite different from the Betazoid version, with an extra paragraph describing various mechanical and RP notes.

`While all Ocampa are telepathic, their short lifespan and rapid development means that a young Ocampa character may not fully develop their abilities until later in life, so it is possible to choose the Talent after character creation. Unlike other telepathic/empathic species, the Ocampa have demonstrated the ability to develop even greater psychic abilities, including precognition, mental projection, telekinesis, and the ability to manipulate matter at a subatomic level.`
